### ISSUE TITLE
Support per player creative permissions..

### ISSUE THREAD

**Issue by Skaapdev** [bell07/minetest-smart_inventory#9]
@bell07 
I figured out a way to disable the contents of the creative page on a per player basis tied to the creative privilege but I have no idea how to hide the creative button. Any ideas of where in the code I could hide the button?

**Comment by bell07** [comment]
@Skaapdev
In a66b9a7299e9e18c4748d0aa06132123827edf53 I added 
`is_visible_func(state) - function for dynamic page enabelling. Should return bool value.`
to the page definition so you can enable the creative button depending on player permissions.

Unfortunately the inventory state is generated once the player is logged in so is not easy to rebuild it dynamlically. The player need log off and re-login in case of permission change

**Comment by bell07** [comment]
Not tested, but this code should work to rebuild the player inventory state without re-login. The code is based on code in smartfs._ldef.inventory  (on_leave + on_join) in smartfs.lua

```
local name = player:get_player_name()
local old_state = smartfs.inv[name]
local form = old_state.def

local new_state = smartfs._makeState_(old_state.def, nil, old_state.location, name)

if form.form_setup_callback(new_state) ~= false then
	old_state.obsolete = true
	smartfs.inv[name] = new_state
	new_state:show()
end
```

**Comment by Skaapdev** [comment]
@bell07 
Wow, Thank you that was very quick :)

With your changes I only did the following get it to work and now it hides the button too. https://github.com/Skaapdev/smart_inventory/commit/8fd9e67266a40684cf8c629a44e1c2bee0855625

I am not really sure about the security repercussions of doing it this way. While hiding the button in `creative.lua` is enough to work I also updated `player.lua` to check player privileges in anyway. Hopefully there is enough checks to prevent exploitation from a malicious client.

I don't envision giving/revoking  creative privileges on a server often so to re-init the player state is not a problem. The player can just logout/login.

On an unrelated question: The screenshots for this project shows the background transparent or opaque. How can I achieve the same as my inventory menu only has a solid default grey background?

Thanks, 
Skaap

**Comment by bell07** [comment]
The screenshots with transparency are from old Minetest version. Since 0.4.7 (?) the transparency was removed from default formspecs. I did not researched which change did it and how to solve it. If you like you can add the transparency again to the mod.

About your change: Looks nice! You can move player_has_creative(state) to new method in `maininv.lua` then reuse them on all places. 
Please do not create local creative = {} because that hides the global creative from creative mod.
You can use new attribute in maininvClass class. Something like (untested)
```
function maininvClass:get_has_creative()
    if self.has_creative == nil then
        self.has_creative = minetest.get_player_privs(self.playername)
    end
    return self.has_creative
end
```
The Method should be available trough 

```
if state.param.invobj:get_has_creative() then
   do creative things
end
```
on all pages.

**Comment by Skaapdev** [comment]
@bell07 

Added your suggestions https://github.com/Skaapdev/smart_inventory/commit/195de2bbfb3f584e727b57b6625ef3c9f0ec61ee and tested, it is working.

Thank you.

**Comment by bell07** [comment]
Thank you! If you are finished with testing you can setup a pull request. So I merge the change to the minetest-mods version.
Did you tested constellations the permission was revoked but the player is still in game?
Unsure in creative_callback(state) in case of permission is away, the return needs to be ""

**Comment by Skaapdev** [comment]
@bell07 
Minor glitch:
When I test removing creative privilege for a player while the player is still online, the inventory falls back to sinv, until I click one of the menu tabs. Then it returns to smart_inventory still with creative abilities.
For my use case this is just a minor glitch. If I do ever remove creative for a player I am happy to kick just to ensure it takes effect. The way I read the code it would be inefficient and wasteful to recheck privilege on every form action to fix the above glitch. Implementing that properly is beyond my current abilities so I am leaving it there.

Creative mode vs Survival mode:
My use case is to run this on a multiplayer server in survival mode. If someone runs this on a creative server, it would mean they would have to do `/grant singleplayer creative` for every player! And if they don't have the creative mod installed their creative mode probably won't work at all. So I have added the creative check back to override the player privilege check when creative_mode is enabled. I have tested both modes again and it is working.

I have created the pull request here https://github.com/minetest-mods/smart_inventory/pull/10

Oh RE - that opacity issue I was able to resolve it by throwing this into an on_player join function:`player:set_formspec_prepend("bgcolor[#FFFFFF32;false]")`

Thanks,
Skaap

**Comment by bell07** [comment]
Interesting the glitch ... Looked for the reason and found it in the "creative" mod. In case of permission change the sfinv update is triggered even the sfinv.enabled is nil. At first I thought to raise an bug report for Minetest Game (owner of creative and of sfinv mod) but decided to solve it in other way, in smartfs framework.. Just a moment...

Found the `function minetest.is_creative_enabled(name)` by the way. Can you please use this method instead of own code in maininvClass:get_has_creative()? The method read permission and setting ..

**Comment by bell07** [comment]
done.. please pull and rebase ;-) Now the creative permission change just trigger page refresh (not rebuild)

Please remove the caching in self.has_creative variable. Then the creative page should be empty if the permission was revoked (untested).. Or just wait, since I have it open in editor ..

**Comment by Skaapdev** [comment]
@bell07 
Not to be boring but I tried your most recent changes. 
I can confirm your fix for the sfinv glitch showing on permission removal is working.  

My game.conf has `creative_mode = false` and a player with creative privilege does not get creative. The
 `return minetest.is_creative_enabled(self.playername)` alone does not work for me.

If I do this it does work:
```
function maininvClass:get_has_creative()
    if minetest.is_creative_enabled(self.playername) == false then
        return minetest.get_player_privs(self.playername).creative
    end
    return minetest.is_creative_enabled(self.playername)
end
```

**Comment by bell07** [comment]
Please check your creative mod installed in your game. The Minetest Game 5.3.0 have the next code in mods/creative/init.lua:
```
function minetest.is_creative_enabled(name)
	if name == "" then
		return old_is_creative_enabled(name)
	end
	return minetest.check_player_privs(name, {creative = true}) or
		old_is_creative_enabled(name)
end
```
As you see the same minetest.check_player_privs() is used. I prefer to update the game / creative mod instead of workaround in Smart Inventory. The Method minetest.is_creative_enabled is used in many other mods and should be used uniformly.

**Comment by Skaapdev** [comment]
@bell07  Ah yes, finally! updating my creative mod to 5.3 worked. Thanks!
